name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: true

jobs:
  validate:
    name: Lint Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        run: pnpm i

      - name: Prettier
        run: pnpm format:check

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
